In [1]:
import pandas as pd
import numpy as np
df= pd.read_csv('titanic.csv')

In [2]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.drop(['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin', 'Embarked'],axis=1, inplace = True)

In [5]:
df.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [10]:
target=df.Survived
inputs = df.drop('Survived', axis =1 )

In [12]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [16]:
inputs=pd.concat([inputs[['Pclass','Age','Fare']], dummies], axis=1)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [17]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [23]:
inputs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Pclass  891 non-null    int64  
 1   Age     714 non-null    float64
 2   Fare    891 non-null    float64
 3   female  891 non-null    uint8  
 4   male    891 non-null    uint8  
dtypes: float64(2), int64(1), uint8(2)
memory usage: 22.7 KB


In [26]:
import math
x=inputs.Age.mean()
x

29.69911764705882

In [30]:
inputs['Age']= inputs.Age.fillna(inputs.Age.mean())
inputs

Pclass        Age     Fare  female  male
0         3  22.000000   7.2500       0     1
1         1  38.000000  71.2833       1     0
2         3  26.000000   7.9250       1     0
3         1  35.000000  53.1000       1     0
4         3  35.000000   8.0500       0     1
..      ...        ...      ...     ...   ...
886       2  27.000000  13.0000       0     1
887       1  19.000000  30.0000       1     0
888       3  29.699118  23.4500       1     0
889       1  26.000000  30.0000       0     1
890       3  32.000000   7.7500       0     1

[891 rows x 5 columns]

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs, target, test_size=0.2, random_state=10)

In [33]:
len(X_test) , len(X_train)

(179, 712)

In [34]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [35]:
model.fit(X_train, y_train)

GaussianNB()

In [36]:
model.score(X_test, y_test)

0.8268156424581006

In [38]:
y_predict=model.predict(X_test[:10])
y_predict[:10] , y_test[:10]

(array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0], dtype=int64),
 590    0
 131    0
 628    0
 195    1
 230    1
 646    0
 75     0
 586    0
 569    1
 287    0
 Name: Survived, dtype: int64)

In [39]:
model.predict_proba(X_test[:10])

array([[9.88386356e-01, 1.16136435e-02],
       [9.86517813e-01, 1.34821869e-02],
       [9.87819352e-01, 1.21806477e-02],
       [1.69366845e-05, 9.99983063e-01],
       [2.50380494e-03, 9.97496195e-01],
       [9.86311511e-01, 1.36884891e-02],
       [9.87645433e-01, 1.23545669e-02],
       [9.73960508e-01, 2.60394920e-02],
       [9.88379286e-01, 1.16207142e-02],
       [9.87084311e-01, 1.29156895e-02]])

#### Exercise

Machine Learning Tutorial - Naive Bayes: Exercise
Use wine dataset from sklearn.datasets to classify wines into 3 categories. Load the dataset and split it into test and train. After that train the model using Gaussian and Multinominal classifier and post which model performs better. Use the trained model to perform some predictions on test data.

In [40]:
from sklearn.datasets import load_wine

In [41]:
wine = load_wine()

In [43]:
dir(wine)

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']

In [49]:
df= pd.DataFrame(wine.data, columns=wine.feature_names )
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [50]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [51]:
df['target'] = wine.target

In [56]:
df.tail()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
173    13.71        5.65  2.45               20.5       95.0           1.68   
174    13.40        3.91  2.48               23.0      102.0           1.80   
175    13.27        4.28  2.26               20.0      120.0           1.59   
176    13.17        2.59  2.37               20.0      120.0           1.65   
177    14.13        4.10  2.74               24.5       96.0           2.05   

     flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
173        0.61                  0.52             1.06              7.7  0.64   
174        0.75                  0.43             1.41              7.3  0.70   
175        0.69                  0.43             1.35             10.2  0.59   
176        0.68                  0.53             1.46              9.3  0.60   
177        0.76                  0.56             1.35              9.2  0.61   

     od280/od315_of_diluted_wines  proline  target  
173                          1.74    740.0       2  
174                          1.56    750.0       2  
175                          1.56    835.0       2  
176                          1.62    840.0       2  
177                          1.60    560.0       2

In [58]:
X=df.drop('target', axis = 1)
y=df.target

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=10)

In [60]:
len(X_train) , len(X_test), len(y_test), len(y_train)

(142, 36, 36, 142)

In [62]:
modelWine=GaussianNB()
modelWine.fit(X_train, y_train)

GaussianNB()

In [64]:
y_predict= modelWine.predict(X_test)
modelWine.score(X_test,y_test)

0.8888888888888888

In [66]:
modelWine.predict_proba(X_test[23:33])

array([[1.00000000e+00, 7.24588015e-20, 5.09387768e-37],
       [8.02311733e-07, 9.99999198e-01, 1.28692643e-17],
       [2.11115040e-27, 1.49310068e-07, 9.99999851e-01],
       [1.95708762e-07, 8.73094178e-01, 1.26905627e-01],
       [1.08323141e-16, 1.23323039e-06, 9.99998767e-01],
       [2.44465163e-14, 9.99146250e-01, 8.53750056e-04],
       [4.11421416e-06, 9.99995886e-01, 4.96269611e-13],
       [5.90347781e-27, 1.72323750e-21, 1.00000000e+00],
       [3.67852162e-22, 1.66297370e-06, 9.99998337e-01],
       [1.00641609e-12, 3.33814925e-01, 6.66185075e-01]])

#### Spam Email detection

In [2]:
import pandas as pd

In [5]:
dfm=pd.read_csv("spam.csv")

In [6]:
dfm.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [7]:
X=dfm.Message

In [8]:
y=dfm.Category

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=10)
